config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :lectures do
    member do
      get :download
      post :comment
      put "like", to: "lectures#upvote"
    put "dislike", to: "lectures#downvote"
    put "spam", to: "lectures#spam_lecture"

    end
  end
  resources :courses
  devise_for :users
  root 'courses#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lecture.rb
class Lecture < ApplicationRecord
    validates :content, presence: true,uniqueness: true
    validates :attachment, presence: true,uniqueness: true
    

    acts_as_commentable
    acts_as_votable

    belongs_to :course

end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: [:download, :show, :edit, :update, :destroy, :spam]
  before_action :authenticate_user!

  # GET /lectures
  # GET /lectures.json
  def index
    @lectures = Lecture.all
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)
    #save file to server
    uploaded_io = params[:lecture][:attachment]
     File.open(Rails.root.join('public','uploads',uploaded_io.original_filename),'wb') do |file|
    file.write(uploaded_io.read)
     end
    @lecture.attachment= uploaded_io.original_filename
      respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'Lecture was successfully created.' }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1
  # PATCH/PUT /lectures/1.json
  def update
    uploaded_io = params[:lecture][:attachment]
    File.open(Rails.root.join('public','uploads',uploaded_io.original_filename),'wb') do |file|
   file.write(uploaded_io.read)
    end
    params[:lecture][:attachment]= uploaded_io.original_filename

    respond_to do |format|

      if @lecture.update(lecture_params)
        
        format.html { redirect_to @lecture, notice: 'Lecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to lectures_url, notice: 'Lecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  def comment
    @lecture = Lecture.find(params[:id])
    @user_who_commented = current_user.id
    comment = Comment.build_from(@lecture, @user_who_commented, params[:comment])
    comment.save
    redirect_to lecture_path
  end

  def download
    extension=@lecture.attachment.split('.')
    send_file Rails.root.join('public','uploads',@lecture.attachment),
    :type=>"application/#{extension[1]}", :x_sendfile=>true
  end 
  def upvote 
    @lecture = Lecture.find(params[:id])
    @lecture.upvote_by current_user
    redirect_to lecture_path
  end  
  
  def downvote
    @lecture = Lecture.find(params[:id])
    @lecture.downvote_by current_user
    redirect_to lecture_path
  end

  

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

   


    # Never trust parameters from the scary internet, only allow the white list through.
    def lecture_params
      params.require(:lecture).permit(:content, :attachment, :course_id)
    end
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/views/lectures/_form.html.erb
<%= form_with(model: lecture, local: true) do |form| %>
  <% if lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.cktext_area :content, id: :lecture_content %>
  </div>


  <div class="field">
    <%= form.label :attachment %>
    <%= form.file_field :attachment, id: :lecture_attachment ,required: true%>
  </div>
  <div class="field">
    <%= form.label :course %>
    <%= form.collection_select :course_id, Course.all, :id, :title  %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lectures</h1>

<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Attachment</th>
      <th scope="col">course</th>

      <th colspan="3" scope="col">action</th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= lecture.attachment %></td>
        <td><%= lecture.course.title %></td>

        <td><%= link_to 'Show', lecture , :class =>'btn btn-success'%></td>
        <td><%= link_to 'Edit', edit_lecture_path(lecture), :class =>'btn btn-info' %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' }, :class =>'btn btn-danger' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecture', new_lecture_path, :class =>'btn btn-warning' %>
<br>
<br>

app/views/lectures/new.html.erb
<h1>New Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Back', lectures_path %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>


  <strong>Content:</strong>
  <div class="alert alert-info" role="alert"> <%= raw @lecture.content %>
</div>
 

<p>
  <strong>Attachment:</strong>
  <%= @lecture.attachment %>
</p>
<%= link_to 'download', download_lecture_path, :class =>'btn btn-info' %>

<p>
  <strong>Course:</strong>
  <%= @lecture.course.title %>

</p>
<strong>Comments:</strong>


<% @lecture.comment_threads.each do |comment| %>
  <div class="alert alert-info" role="alert">
 <span style="color:red"> <%= comment.user.name %> </span>: <%= comment.body %>
  </div>
<% end %>

 <%= form_tag comment_lecture_path, :method => :post do %>

<%= text_field_tag "comment" %>

<%= submit_tag "comment" , :class =>'btn btn-success'%>
<% end %>
<br>
<%= link_to dislike_lecture_path(@lecture), :class =>'btn btn-success', method: :put do %>
  dislike
  <%= @lecture.get_downvotes.size %>
  <% end %>

<%= link_to like_lecture_path(@lecture), :class =>'btn btn-info', method: :put do %>
  like
  <%= @lecture.get_upvotes.size %>
<% end %>


<%= link_to 'Edit', edit_lecture_path(@lecture), :class =>'btn btn-success' %> |
<%= link_to 'Back', lectures_path , :class =>'btn btn-warning'%>